### ISSUE TITLE
Missing for Milestone 1

### ISSUE THREAD

**Issue by yncyrydybyl** [polychatproject/polychat-appservice#1]
- [ ] set alias for mainroom
- [ ] write id into mainroom as roomstate
- [x] create bridge via invite bridgebot (create subroom, invite @irc_bot:synapse, chat with @irc_bot:synapse: `!plumb !WVghNiBsbxPYWOYzhm:synapse inspircd #ircname `)
- [ ] persist the changed nick into the subroom like described "### Interludium: user identities" in implementation_plan.md
