### ISSUE TITLE
Bridge join/ leave events

### ISSUE THREAD

**Issue by jaller94** [polychatproject/polychat-appservice#7]
- [ ] If a Polychat user joins or leaves a Sub Room, bridge this to the main room.
- [ ] If a user joins or leaves the Main Room, send a notice to all Sub Rooms (except the Sub Room of the joining/leaving user).

**Comment by jaller94** [comment]
Implemented but untested

## Todo
- [ ] In sub rooms, show the Polychat user's display name instead of their MXID.

**Comment by jaller94** [comment]
2024-08-31: Removed join, leave and ban messages because they use the MXID instead of display name and get posted on every update to the state membership state event. https://github.com/polychatproject/polychat-appservice/commit/bf18d49f0f999b79721a56c78c5f6b06fd188bf5
